// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI6bgTVza08nEeVeT20ttWoWzaZz9mK5g',
    appId: '1:203740301773:web:4680bc1d51e0207f65dc84',
    messagingSenderId: '203740301773',
    projectId: 'medex-49d69',
    authDomain: 'medex-49d69.firebaseapp.com',
    storageBucket: 'medex-49d69.firebasestorage.app',
    measurementId: 'G-59QH32JD1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9N5UjKry0EnXcnW_QLRc3MNVPnHrXmkk',
    appId: '1:203740301773:android:2fcaa9bec8e5bc2a65dc84',
    messagingSenderId: '203740301773',
    projectId: 'medex-49d69',
    storageBucket: 'medex-49d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGZ9JKuUZMLU3fh8uOLlbbcqIDv9oRj0',
    appId: '1:203740301773:ios:c98fbf2c15be7f8165dc84',
    messagingSenderId: '203740301773',
    projectId: 'medex-49d69',
    storageBucket: 'medex-49d69.firebasestorage.app',
    iosBundleId: 'com.example.medex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiGZ9JKuUZMLU3fh8uOLlbbcqIDv9oRj0',
    appId: '1:203740301773:ios:c98fbf2c15be7f8165dc84',
    messagingSenderId: '203740301773',
    projectId: 'medex-49d69',
    storageBucket: 'medex-49d69.firebasestorage.app',
    iosBundleId: 'com.example.medex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI6bgTVza08nEeVeT20ttWoWzaZz9mK5g',
    appId: '1:203740301773:web:d3e3c252ccef6e7a65dc84',
    messagingSenderId: '203740301773',
    projectId: 'medex-49d69',
    authDomain: 'medex-49d69.firebaseapp.com',
    storageBucket: 'medex-49d69.firebasestorage.app',
    measurementId: 'G-21QVFPDWCQ',
  );
}
